version: '3'
services:
  db1:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/data
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"


  app-prof:
    container_name: prof
    build:
      context: ./app/
    restart: always
    depends_on:
      - db1
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      POSTGRES_HOST: db1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "4000:4000"
    networks:
      - app-network


  app-auth:
    container_name: auth
    build:
      context: ./auth/
    restart: always
    depends_on:
      - db1
      - rabbitmq

    environment:
      RABBITMQ_HOST: rabbitmq
      POSTGRES_HOST: db1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
